### ISSUE TITLE
images are created with 0600 /nix and /nix/store

### ISSUE THREAD

**Issue by disassembler** [nlewo/nix2container#12]
This breaks any images that need to run as non-root.

```
bash-5.1# ls -hal /nix
total 12K
drw-------   3 0 0   19 Mar 18 08:51 .
drwxr-xr-x  14 0 0  175 Mar 18 08:52 ..
drw------- 107 0 0 8.0K Mar 18 08:52 store
```

**Comment by nlewo** [comment]
Hm i'm surprised because I'm running non root images and i didn't observe this.

```
$ nix run -L .#examples.bash.copyToPodman
Copy to podman image bash:16xfk5dbhraq19h9pk3lnhnnpa3f4xkh
Getting image source signatures
...
...
$ podman run bash:16xfk5dbhraq19h9pk3lnhnnpa3f4xkh ls -lah /nix
drwxr-xr-x  3 0 0 4.0K Feb 16 21:34 .
dr-xr-xr-x 12 0 0 4.0K Mar 18 17:13 ..
drwxr-xr-x 12 0 0 4.0K Feb 16 21:34 store
```

I'm still trying to undestand what could happen...

**Comment by nlewo** [comment]
What are the permissions on an actual storepaths?
For instance:
```
podman run  bash:16xfk5dbhraq19h9pk3lnhnnpa3f4xkh ls -lah /nix/store/8kgsjv57icc18qhpmj588g9x1w34hi4j-bash-interactive-5.1-p12
```

Actually, `/nix` and `/nix/store` directory are not explicitly referenced in the tar. Maybe we need to reference them.

**Comment by nlewo** [comment]
The same issue on `dockerTools.buildImage` has been fixed by adding them in the tar: https://github.com/NixOS/nixpkgs/pull/38837

**Comment by Profpatsch** [comment]
Is this a MacOS/nix store with user permissions issue?

**Comment by nlewo** [comment]
@disassembler https://github.com/nlewo/nix2container/pull/14 should fix this issue. Could you try it on your setup?
```
$ nix run github:nlewo/nix2container/create-nix-store#examples.bash.copyToPodman
$ podman run bash:9jcl1wxl5l8z3pklz235ngycc7gyqgvb ls -l /nix
drwxr-xr-x 12 0 0 4096 Jan  1  1970 store
```
