### ISSUE TITLE
Layers with symlinks differ depending on OS

### ISSUE THREAD

**Issue by YorikSar** [nlewo/nix2container#23]
I've noticed that when I run patched skopeo on Linux, it succeeds, but when I run it with the same JSON on Darwin, I get
```
FATA[0001] writing blob: writing to temporary on-disk layer: happened during read: Digest did not match, expected sha256:..., got sha256:...
```
And the layer in question is a `.so` library that has symlinks in it.

It looks like nix2containers produces different hashes on different OSs if the layer contains symlinks. To check this theory, I've added a symlink to test data and ran in on two different systems, I got on Darwin:
```
$ ln -s file1 data/tar-directory/symlink; go test ./nix -run TestTar
--- FAIL: TestTar (0.00s)
    tar_test.go:19: Digest is sha256:9a9402c601020cb24b71d4287b143d7bda875869970a1ed35792caa1702fdb69 while it should be sha256:efccbbe35209d59cfeebd8e73785258d3679fa258f72a7dfbc2eec65695fd5c8
FAIL
FAIL    github.com/nlewo/nix2container/nix      0.244s
FAIL
```
And on Linux:
```
$ ln -s file1 data/tar-directory/symlink; go test ./nix -run TestTar
--- FAIL: TestTar (0.00s)
    tar_test.go:19: Digest is sha256:077af73ad0fb226436e92a272318b777b6976b85c3a05d86183274818dd634f8 while it should be sha256:efccbbe35209d59cfeebd8e73785258d3679fa258f72a7dfbc2eec65695fd5c8
FAIL
FAIL    github.com/nlewo/nix2container/nix      0.013s
FAIL
```

Note that the digests are different in both cases, even though they should match. Without this symlink, test passes, so the digests are the same.

Note that this prevents me from using nix2container on macOS with Linux builder.

**Comment by nlewo** [comment]
@YorikSar Thx for this nice bug report!

I never used Darwin and i don't know what could differ regarding symlinks...

If you set `reproducible=false` in a nix2container image or layer, the produced store path contains the JSON file and the tar file. This could allow us to diff the two produced tar files in order to know what differs (with `tar -tvf` for instance).

It would be really useful if you could provide such diff on a simple image (containing a symlink) built on Linux and Darwin!

**Comment by YorikSar** [comment]
Digging a bit deeper, I found that the NAR format is only described in [Eelco's thesis](https://edolstra.github.io/pubs/phd-thesis.pdf) and it includes following wording (on page 90 of the thesis, 98 of the PDF):

> Fortunately, for our purposes—which is storing components in the Nix store—most of these features are either not relevant (drive letters, device nodes, etc.), can be ignored (hard links), or are never used in practice (streams). Some others, such as **permissions, we will ignore to make life simpler**.

He then proceeds with describing NAR format that indeed ignores all permissions except the executable flag on regular files. Since NAR format is used to transfer store paths between machines, we can expect to have such discrepancies in the OS-dependant things like symlinks (and they are, very much, OS-dependant, as it appears).

I guess since it's impossible to change symlink permissions on Linux, and Docker always (*) runs on Linux, and Nix doesn't care about permissions anyway, we should be forcing symlink permissions to 777 in layers.

(*) Docker can natively run containers on Linux and Windows, and I know of effort to bring it to FreeBSD. FreeBSD is officially not supported by Docker, and efforts to run Docker on it without emulation didn't get anywhere (yet?). Windows is not supported by Nix ([yet?](https://github.com/nix-windows/nix)), and doesn't really have Unix permissions. I don't know of other container runtimes that can run outside Linux.

**Comment by YorikSar** [comment]
Created a PR with a fix for this.
