### ISSUE TITLE
Avoid pulling dependencies from entrypoint

### ISSUE THREAD

**Issue by jmgilman** [nlewo/nix2container#42]
Take the following example:

```nix
{
  inputs.nix2container.url = "github:nlewo/nix2container";
  inputs.nixpkgs.follows = "nix2container/nixpkgs";

  outputs = { self, nixpkgs, nix2container }:
    let
      pkgs = import nixpkgs { system = "aarch64-linux"; };
      n2c = nix2container.packages.aarch64-linux.nix2container;
      entrypoint = pkgs.writeShellApplication {
        name = "entrypoint";
        runtimeInputs = [ pkgs.git ];
        text = ''
          git --help
        '';
      };
    in
    {
      packages.aarch64-linux.hello = n2c.buildImage {
        maxLayers = 100;
        name = "hello";
        config = {
          entrypoint = [ "${entrypoint}/bin/entrypoint" ];
        };
      };
    };
}
```

This will build an image whose layers follow this rough pattern:

1. `git` dependencies
2. Entrypoint derivation

If I were to set `maxLayers` to the default value, then `git` and the entrypoint derivation would be put in the same layer. The problem is that increasing `maxLayers` does not seem to guarantee that the entrypoint derivation will be in its own layer (it really depends on how large its dependencies are). Is there a way I can avoid pulling in the dependencies of the entrypoint so that I can put them in a separate layer? 

I tried something like this:

```nix
{
  inputs.nix2container.url = "github:nlewo/nix2container";
  inputs.nixpkgs.follows = "nix2container/nixpkgs";

  outputs = { self, nixpkgs, nix2container }:
    let
      pkgs = import nixpkgs { system = "aarch64-linux"; };
      n2c = nix2container.packages.aarch64-linux.nix2container;
      entrypoint = pkgs.writeShellApplication {
        name = "entrypoint";
        runtimeInputs = [ pkgs.git ];
        text = ''
          git --help
        '';
      };
    in
    {
      packages.aarch64-linux.hello = n2c.buildImage {
        maxLayers = 100;
        name = "hello";
        config = {
          entrypoint = [ "${entrypoint}/bin/entrypoint" ];
        };
        layers = [
          (n2c.buildLayer {
            deps = [ pkgs.git ];
          })
        ];
      };
    };
}
```

It does isolate the dependencies into a single layer, but it puts the entrypoint layer *before* the dependency layer. I'm new to making Docker containers with Nix, does the order of layers event matter when using `nix2container`?

Any help is appreciated, thanks!

**Comment by nlewo** [comment]
@jmgilman No, the layer ordering doesn't matter. Does this answer enough to fix your issue?

**Comment by jmgilman** [comment]
Yes, that helps me figure out where my optimizations should be focused. Thank you!
