### ISSUE TITLE
Allow changing ownership

### ISSUE THREAD

**Issue by jmgilman** [nlewo/nix2container#44]
It appears that all paths are [set to root](https://github.com/nlewo/nix2container/blob/master/nix/tar.go#L97-L100) as the owner by default with no way to interrupt this behavior. Since we can [already modify the file permissions](https://github.com/nlewo/nix2container/blob/master/nix/tar.go#L112), it would be nice to also control the file ownership. 

In a lot of containers, a default (non-root) user is created with a working directory that they have ownership over. As far as I know, it's not currently possible to emulate this with `nix2container`. Note that the nix [docker tools has `fakeRootCommands`](https://github.com/NixOS/nixpkgs/pull/116749) to more or less emulate this. 

Is this something we can add to `nix2container`?

**Comment by nlewo** [comment]
@jmgilman yes, that would definitively be nice to add this to `nix2container`. Moreover, as you said, it should not be a big deal since we could add file ownership data to the `perms` data structure.
