### ISSUE TITLE
Use sudo/doas if permission denied while trying to connect to the Docker daemon socketpermission denied while trying to connect to the Docker daemon socket

### ISSUE THREAD

**Issue by vdot0x23** [nlewo/nix2container#56]
I think some users do not give themselves direct access to the docker daemon so a feature like this could be handy.

Could maybe be implemented by wrapping the scripts here https://github.com/nlewo/nix2container/blob/b008fe329ffb59b67bf9e7b08ede6ee792f2741a/default.nix#L44-L64

In  a script such as this:

```sh
#!/bin/sh
# shellcheck disable=SC2068
# ^ Intentionally unquoted arugments

permission() {
  # "Server" is only present if we have docker permissions
  if docker version 2> /dev/null | grep -q Server > /dev/null 2>&1; then
    return 0
  else
    return 1
  fi
}

if permission; then
  $@
elif command -v sudo > /dev/null 2>&1; then
  sudo $@
elif command -v doas > /dev/null 2>&1; then
  doas $@
fi
```

I'm sure there is a better way to check for permission than the above and I'm not sure if the highlighted scripts from `default.nix` are the only places where using sudo/doas may be relevant. Perhaps it could be interesting to explore? :)

**Comment by nlewo** [comment]
@vdot0x23 Hm, i don't think this is a common use case (IIRC, a lot of Linux distributions provide the Docker group for this purpose). Moreover, I don't really like to use sudo in scripts without big warnings.

For your needs, i think you could easily build your own script by using the skopeo derivation exposed by the nix2container flake.
