### ISSUE TITLE
Empty history can cause issues with certain tools

### ISSUE THREAD

**Issue by armeenm** [nlewo/nix2container#57]
Some tools need a history entry per layer (Artifactory, in particular). An empty history works, but if you try to create an image via a traditional Dockerfile using a nix2container-built image with n layers as a base, this will produce an image with n+1 layers but only 1 history entry, thus leading to "manifest invalid" errors on push. This issue is more well documented [here](https://github.com/GoogleContainerTools/jib/issues/534) and in the eventual fix [here](https://github.com/GoogleContainerTools/jib/pull/877). Perhaps we can populate the image history with simple `created_by` entries of "nix2container" or similar as a quick fix and potentially allow for custom entries later on.

**Comment by nlewo** [comment]
@armeenm Thx for your bug report.

That's pretty stupid because it's an optional attribute!

Anyway, #58 should fix this. Could you please give it a try?

**Comment by armeenm** [comment]
#58 works for me. Thank you!
