### ISSUE TITLE
Cannot connect to the docker daemon when running on rootless installation

### ISSUE THREAD

**Issue by ghostbuster91** [nlewo/nix2container#62]
Hi,

When trying to build a docker image using `nix2container` I am always getting: 
```
 Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
I think that this is because I have installed docker as a non-root user (https://docs.docker.com/engine/security/rootless/)

Skopeo under the hood uses `unix:///var/run/docker.sock` as a default location for the socket but on my machine the socket is in:
```
unix:///run/user/1000/docker.sock
```

This location can be however overridden by providing `--src-daemon-host=...` option when interacting with skopeo. 

Now, I could implement that but I am not sure what is the best way to approach that in your project. 
We would have to somehow pass it into:
```
  copyToDockerDaemon = image: pkgs.writeShellScriptBin "copy-to-docker-daemon" ''
    echo "Copy to Docker daemon image ${image.imageName}:${image.imageTag}"
    ${skopeo-nix2container}/bin/skopeo --insecure-policy copy nix:${image} docker-daemon:${image.imageName}:${image.imageTag}
    ${skopeo-nix2container}/bin/skopeo --insecure-policy inspect docker-daemon:${image.imageName}:${image.imageTag}
  '';
```

Which means either adding another parameter or extracting that information from environment variable. I am not a fan of the latter and I only mention it for the sake of completeness. 

I am afraid that there is no option to add another parameter without introducing a breaking change :(

Here we have few options again:
1. Add it to `copyToDockerDaemon` and similar like 
   ```
   copyToDockerDaemon = image: daemon: ...
   ```
3. Convert the function parameter to a set and add it there
   ```
   copyToDockerDaemon = { image, daemon }: 
   ```
4. Since it is a parameter that is common for multiple commands we could provide it earlier
   ```
   someWrapper= daemon: 
      copyToDockerDaemon = image: ...
   ```

I am not a nix expert so I am not really sure which one is the most suitable. Let me know what do you think.

**Comment by nlewo** [comment]
Since this depends on your environment, i don't think we should do that at build time.

Maybe we could just use `$@` allowing  the user to provide additional Skopeo arguments. This however means we should not have both the Skopeo `copy` and `inspect` in the same script.

We could then have something such as:
```
copyToDockerDaemon = image: pkgs.writeShellScriptBin "copy-to-docker-daemon" ''
    echo "Copy to Docker daemon image ${image.imageName}:${image.imageTag}"
    ${skopeo-nix2container}/bin/skopeo --insecure-policy copy nix:${image} docker-daemon:${image.imageName}:${image.imageTag} $@
  '';
```

We should then be able to run:
```
nix run .#image.copyToDockerDaemon -- --some-skopeo-option
```

WDYT?

**Comment by ghostbuster91** [comment]
> Since this depends on your environment, i don't think we should do that at build time.

You are totally right, I got confused about that. 

> Maybe we could just use $@ allowing the user to provide additional Skopeo arguments. This however means we should not have both the Skopeo copy and inspect in the same script.

Yes I think that would be the best option. Also since that is a runtime configuration I actually think that using an environment variable would we fine as well. By convention `DOCKER_HOST` should point to a socket address. So we could do 
```
socket = if DOCKER_HOST then DOCKER_HOST else unix:///var/run/docker.sock
${skopeo-nix2container}/bin/skopeo --insecure-policy copy nix:${image} docker-daemon:${image.imageName}:${image.imageTag} -- --src-daemon-host=$socket
```

which would be slightly more convenient but that is nothing mandatory.

**Comment by blaggacao** [comment]
From face value, I can't tell if the use case here is _also_ channeled through `std`. If that's the case and in order to take off a little bit of upstream maintenance burdon, we _may_ also consider this to be responsibility of the Container Block Type as in [this comment](https://github.com/nlewo/nix2container/issues/61#issuecomment-1381106953).

If this isn't channeled through `std`, I haven't said anything :smile:

**Comment by nlewo** [comment]
> By convention DOCKER_HOST should point to a socket address

@ghostbuster91 I would prefer to stick as close as possible to the Skopeo tool (i suppose `DOCKER_HOST` is not supported by Skopeo). So, from my point of view, adding `$@` is the best approach.

**Comment by ghostbuster91** [comment]
@blaggacao Yes, `std` was involved here :) Sure, I will add it there but first a change to `nix2container` was required so that it could pass additional parameters downstream skopeo.
